config/routes.rb
Rails.application.routes.draw do

   root 'contact_forms#index'
   resources :contact_forms

end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base

  FAILURE = 'Failure'
  DAMAGE = 'Damage'
  FAULT = 'Fault'

  CATEGORIES = [FAILURE, DAMAGE, FAULT]

  validates :category, presence: true, inclusion: { in: CATEGORIES }
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: EMAIL_REGEX }
  validates :description, presence: true, length: { minimum: 100 }

  before_create :set_fields

  def set_fields
    now = Time.now

    case category when FAILURE
      if now.hour.between?(9,16)
        self.price = 50
      else
        self.price = 100
      end
      self.ect = now + 4.hours
    when DAMAGE
      self.price = 10
      self.ect = now + 24.hours
    when FAULT
      self.price = 1
      self.ect = now + 72.hours
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController

  def index
    @contact_forms = ContactForm.all
  end

  def new
    @contact_form = ContactForm.new
  end

  def create
    @contact_form = ContactForm.new(contact_form_params)
    if @contact_form.save
      flash.now[:success] = "Form sent successfully!"
      redirect_to contact_forms_path
    else
      flash.now[:error] = "Something went wrong, send your form once again"
      render :new
    end
  end

  def show
    @contact_form = ContactForm.find(params[:id])
    @contact_form.message_read = true
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(:email, :description, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact_forms/index.html.haml
%div#prelude
  %h3 Welcome! If your machine has just broken down, you're in a good place. We are here for you 24hrs/day. Speed, low prices and effects - this is what you should expect ;-)

%div#image
  =image_tag "TechSupportCat.jpg"

app/views/contact_forms/new.html.haml
%div.form
  = simple_form_for @contact_form do |f|
    = f.input :email, required: true, pattern: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, placeholder: 'user@domain.com'
    = f.input :description, required: true, input_html: { minlength: 100 }
    = f.input :category, collection: ContactForm::CATEGORIES, prompt: 'Choose...', required: true
    %div#submit
      = f.submit 'Wyślij zgłoszenie'

%div.navigation
  =link_to 'Go back', root_path

app/views/contact_forms/show.html.haml
%h4= @contact_form.email
%p= @contact_form.description
%p= @contact_form.category

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Report A Problem
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %div.header
      %h1= link_to 'REPORT YOUR PROBLEM', new_contact_form_path
      %h2 WE WILL FIX IT

    = yield